import { Component, OnInit, inject, signal } from "@angular/core";
import { FormBuilder, Validators } from "@angular/forms";
import { provideNativeDateAdapter } from "@angular/material/core";
import { MatProgressSpinnerModule } from "@angular/material/progress-spinner";
import { ActivatedRoute, Router } from "@angular/router";
import { ApiResponse } from "../../../../core/models";
import { SharedModule } from "../../../../core/modules/shared.module";
import { Country } from "../../models/country.model";
import { CountryService } from "../../services/country.service";

type FormMode = 'create' | 'edit' | 'view';
@Component({
  selector: 'app-country-form',
  standalone: true,
  imports: [SharedModule, MatProgressSpinnerModule],
  providers: [provideNativeDateAdapter()],
  templateUrl: './country-form.html',
  styleUrls: ['./country-form.scss']
})
export class CountryForm implements OnInit {
  private readonly fb = inject(FormBuilder);
  private readonly service = inject(CountryService);
  private readonly route = inject(ActivatedRoute);
  private readonly router = inject(Router);
    readonly mode = signal<FormMode>('create');

  objectKeys = Object.keys;

  readonly loading = signal<boolean>(false);
  readonly countryId = signal<number | null>(null);
    readonly validationMessages: Record<string, Record<string, string>> = {
    countryId: {
      required: 'This field is required',
    },
    name: {
      maxlength: 'Maximum length is 100 characters',
    },
 
  };
  
  
  

  readonly form = this.fb.nonNullable.group({
    countryId: [0, [Validators.required]],
    name: ['', [Validators.maxLength(100)]],

  });

  

  ngOnInit(): void {
      const mode = this.route.snapshot.data['mode'] as FormMode | undefined;
          if (mode) {
      this.mode.set(mode);
    }
  
    
    const id = Number(this.route.snapshot.paramMap.get('id'));
    if (id) {
      this.countryId.set(id);
      this.loadDetails(id);
    }
    if (this.mode() === 'view') {
      this.form.disable({ emitEvent: false });
    }
  }

  

  loadDetails(id: number): void {
    this.loading.set(true);
    this.service.getCountryDetails(id).subscribe({
      next: (res: ApiResponse<Country>) => {
        if (res.data) {
        
          this.form.patchValue(res.data);
       if (this.mode() === 'view') {
          this.form.disable({ emitEvent: false });
          
          }

        }
        this.loading.set(false);
      },
      error: () => this.loading.set(false)
    });
  }

    getErrorMessage(controlName: string): string {
    const control = this.form.get(controlName);
    if (!control || !control.errors) return '';
    
    const firstErrorKey = Object.keys(control.errors)[0];
    return this.validationMessages[controlName]?.[firstErrorKey] || 'Invalid field';
  }

  onSubmit(): void {
      if (this.mode() === 'view') return;
    if (this.form.invalid) {
      this.form.markAllAsTouched();
      return;
    }

    this.loading.set(true);

    // Dynamic Mapping Logic generated by GetFormMappingLogic()
    const rawValue = this.form.getRawValue() as Country;
    const model: Country = {
      ...rawValue,
      countryId: this.countryId() ?? 0,

    };

const id = this.countryId();
    const request$ = id 
      ? this.service.updateCountry(model) 
      : this.service.addCountry(model);

    request$.subscribe({
      next: () => this.onCancel(),
      error: () => this.loading.set(false),
      complete: () => this.loading.set(false)
    });
  }

  onCancel(): void {
    // Navigating back to the absolute path of the list page
    this.router.navigate(['/country']);
  }
}