import { Component, OnInit, inject, signal } from "@angular/core";
import { FormBuilder, Validators } from "@angular/forms";
import { provideNativeDateAdapter } from "@angular/material/core";
import { MatProgressSpinnerModule } from "@angular/material/progress-spinner";
import { ActivatedRoute, Router } from "@angular/router";
import { ApiResponse } from "../../../../core/models";
import { SharedModule } from "../../../../core/modules/shared.module";
import { State } from "../../models/state.model";
import { StateService } from "../../services/state.service";


type FormMode = 'create' | 'edit' | 'view';
@Component({
  selector: 'app-state-form',
  standalone: true,
  imports: [SharedModule, MatProgressSpinnerModule, CountryDropdown],
  providers: [provideNativeDateAdapter()],
  templateUrl: './state-form.html',
  styleUrls: ['./state-form.scss']
})
export class StateForm implements OnInit {
  private readonly fb = inject(FormBuilder);
  private readonly service = inject(StateService);
  private readonly route = inject(ActivatedRoute);
  private readonly router = inject(Router);
    readonly mode = signal<FormMode>('create');

  objectKeys = Object.keys;

  readonly loading = signal<boolean>(false);
  readonly stateId = signal<number | null>(null);
    readonly validationMessages: Record<string, Record<string, string>> = {
    name: {
      required: 'This field is required',
      maxlength: 'Maximum length should be 50',
      pattern: 'Invalid format',
    },
    countryId: {
      required: 'This field is required',
    },
 
  };
  
  
  

  readonly form = this.fb.nonNullable.group({
    name: ['', [Validators.required, Validators.maxLength(50), Validators.pattern('^[a-zA-Z0-9-,.`\']*$')]],
    countryId: [0, [Validators.required]],

  });

  

  ngOnInit(): void {
      const mode = this.route.snapshot.data['mode'] as FormMode | undefined;
          if (mode) {
      this.mode.set(mode);
    }
  
    
    const id = Number(this.route.snapshot.paramMap.get('id'));
    if (id) {
      this.stateId.set(id);
      this.loadDetails(id);
    }
    if (this.mode() === 'view') {
      this.form.disable({ emitEvent: false });
    }
  }

  

  loadDetails(id: number): void {
    this.loading.set(true);
    this.service.getStateDetails(id).subscribe({
      next: (res: ApiResponse<State>) => {
        if (res.data) {
        
          this.form.patchValue(res.data);
       if (this.mode() === 'view') {
          this.form.disable({ emitEvent: false });
          
          }

        }
        this.loading.set(false);
      },
      error: () => this.loading.set(false)
    });
  }

    getErrorMessage(controlName: string): string {
    const control = this.form.get(controlName);
    if (!control || !control.errors) return '';
    
    const firstErrorKey = Object.keys(control.errors)[0];
    return this.validationMessages[controlName]?.[firstErrorKey] || 'Invalid field';
  }

  onSubmit(): void {
      if (this.mode() === 'view') return;
    if (this.form.invalid) {
      this.form.markAllAsTouched();
      return;
    }

    this.loading.set(true);

    // Dynamic Mapping Logic generated by GetFormMappingLogic()

    const rawValue = this.form.getRawValue() as State;

    const baseModel: State = {
      name: rawValue.name ?? '',
      countryId: rawValue.countryId ?? 0,
    };

    const id = this.stateId();

    const model: State = id
      ? { ...baseModel, stateId: id }
      : baseModel;


const id = this.stateId();
    const request$ = id 
      ? this.service.updateState(model) 
      : this.service.addState(model);

    request$.subscribe({
      next: () => this.onCancel(),
      error: () => this.loading.set(false),
      complete: () => this.loading.set(false)
    });
  }

  onCancel(): void {
    // Navigating back to the absolute path of the list page
    this.router.navigate(['/state']);
  }
}